const { MigrationInterface } = require('typeorm');

class CreateWalletLimitsTable1682023456789 {
  async up(queryRunner) {
    await queryRunner.query(`
            CREATE TABLE wallet_limits (
                id varchar(36) NOT NULL PRIMARY KEY,
                category varchar(255) NULL,
                amount float NULL,
                type ENUM('weekly','daily','monthly','yearly') DEFAULT 'monthly',
                walletId varchar(36) NOT NULL,
                isAutoGenerated boolean DEFAULT false
            );
        `);
  }

  async down(queryRunner) {
    await queryRunner.query(`DROP TABLE wallet_limits`);
  }
}

CreateWalletLimitsTable1682023456789.prototype.name =
  'CreateWalletLimitsTable1682023456789';

module.exports = { CreateWalletLimitsTable1682023456789 };
